"use client";

import { useMemo, useState } from "react";
import type { CognitiveResponse } from "@/lib/elo-cognitive";

type Props = { onSignOut?: () => void; accessToken: string };
type AreaId = "orquestrador" | "dashboard" | "comercial" | "almoxarifado" | "compras" | "producao" | "pcp" | "expedicao" | "catalogo" | "chat" | "notificacoes" | "configuracoes";
type Area = { id: AreaId; icon: string; label: string; eyebrow: string; title: string; description: string; source: string; cards: string[]; };

const areas: Area[] = [
  { id: "orquestrador", icon: "◈", label: "Orquestrador", eyebrow: "ELO · Orquestração", title: "Orquestrador de decisões", description: "Coordena intenção, evidência, política e encaminhamento entre as áreas.", source: "Missões do ELO Cognitivo", cards: ["Missões", "Decisões", "Aprendizado"] },
  { id: "dashboard", icon: "▦", label: "Dashboard", eyebrow: "ELO · Comercial", title: "Dashboard Comercial", description: "Visão de solicitações, propostas e riscos quando houver fonte operacional conectada.", source: "Solicitações e propostas", cards: ["Solicitações", "Propostas", "Riscos"] },
  { id: "comercial", icon: "◉", label: "Comercial", eyebrow: "ELO · Comercial", title: "Comercial", description: "Solicitações, demanda sazonal e movimentação de clientes.", source: "Dados comerciais autorizados", cards: ["Solicitações", "Demanda", "Clientes"] },
  { id: "almoxarifado", icon: "□", label: "Almoxarifado", eyebrow: "ELO · Operação", title: "Almoxarifado", description: "Estoque, separação e pedidos de material com saldo rastreável.", source: "Lotes e movimentações", cards: ["Estoque", "Reservas", "Alertas"] },
  { id: "compras", icon: "⌁", label: "Compras", eyebrow: "ELO · Suprimentos", title: "Compras", description: "Cotações, fornecedores, lead time e pedidos de compra.", source: "Cotações e ordens de compra", cards: ["Cotações", "Pedidos", "Fornecedores"] },
  { id: "producao", icon: "▤", label: "Produção", eyebrow: "ELO · Produção", title: "Produção", description: "Ordens de fabricação, etapas do fluxo e inspeções.", source: "OFs e eventos de produção", cards: ["Ordens", "Etapas", "Inspeções"] },
  { id: "pcp", icon: "▧", label: "Planejamento/PCP", eyebrow: "ELO · Planejamento/PCP", title: "Planejamento/PCP", description: "O Orçamento é setor interno: solicitações, Checklist ELO, composição documentada e revisão.", source: "SO, catálogo e diretrizes", cards: ["Solicitações", "Checklist", "Orçamento"] },
  { id: "expedicao", icon: "↗", label: "Expedição", eyebrow: "ELO · Operação", title: "Expedição", description: "Programação de expedição, quarentena, retorno de ativos e campo.", source: "Expedições e devoluções", cards: ["Expedições", "Quarentena", "Retornos"] },
  { id: "catalogo", icon: "▥", label: "Catálogo", eyebrow: "ELO · Conhecimento técnico", title: "Catálogo", description: "Taxonomia, modelos, lista-mãe, BOM e diretório técnico.", source: "Taxonomia e Lista-Mãe", cards: ["Taxonomia", "Modelos", "Composição"] },
  { id: "chat", icon: "◌", label: "Chat", eyebrow: "ELO · Comunicação", title: "Chat da equipe", description: "Comunicação setorial com rastreabilidade e sem envio externo implícito.", source: "Canal autorizado", cards: ["Conversas", "Menções", "Registros"] },
  { id: "notificacoes", icon: "!", label: "Notificações", eyebrow: "ELO · Governança", title: "Notificações", description: "Pendências, evidência, autorização e resultado provenientes de eventos rastreáveis.", source: "Eventos de governança", cards: ["Pendências", "Autorizações", "Eventos"] },
  { id: "configuracoes", icon: "⚙", label: "Configurações", eyebrow: "ELO · Administração", title: "Configurações", description: "Diretrizes, escopos, integrações e limites do workspace.", source: "Perfis e políticas", cards: ["Diretrizes", "Acessos", "Integrações"] }
];

const checklist = ["Modelo e escopo", "Materiais e adaptações", "Elétrica", "Água, esgoto e drenagem", "Implantação e logística", "Acessibilidade e uso", "Padrão × excedente", "Riscos e responsabilidades", "Alternativas e lacunas"];

function StateCard({ label }: { label: string }) {
  return <article className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-4 shadow-sm"><p className="text-xs text-slate-500">{label}</p><strong className="mt-3 block text-base">Sem dado conectado</strong><p className="mt-2 text-xs leading-5 text-slate-500">Aguardando fonte canônica e permissão de acesso.</p></article>;
}

function GenericArea({ area, onOpenPCP }: { area: Area; onOpenPCP: () => void }) {
  return <div className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-[var(--elo-panel)] p-6 shadow-sm lg:p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">{area.eyebrow}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{area.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-500">{area.description}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{area.cards.map((label) => <StateCard key={label} label={label} />)}</div></section>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
      <section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{area.title} · fila operacional</h3><p className="mt-1 text-sm text-slate-500">Nenhum registro operacional é exibido sem uma fonte integrada.</p></div><span className="rounded-full border border-slate-200 px-3 py-1 text-xs font-semibold text-slate-500">Estado vazio correto</span></div><div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><p className="font-semibold">Aguardando conexão governada</p><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">A tela está pronta para {area.source.toLowerCase()}. Nenhum volume, saldo, ordem, mensagem ou indicador foi criado para preencher a interface.</p></div></section>
      <aside className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><h3 className="font-semibold">Limites aplicados</h3><ul className="mt-4 space-y-3 text-sm leading-5 text-slate-600"><li>• Ações externas exigem autorização.</li><li>• A fonte deve preservar tenant e principal.</li><li>• Evidência e resultado permanecem rastreáveis.</li></ul>{area.id !== "pcp" && <button type="button" onClick={onOpenPCP} className="mt-6 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold hover:bg-slate-50">Abrir Planejamento/PCP</button>}</aside>
    </div>
  </div>;
}

function PCPWorkspace({ onMission }: { onMission: (text: string) => void }) {
  const [stage, setStage] = useState<"solicitacao" | "checklist" | "orcamento" | "revisao">("solicitacao");
  const [so, setSO] = useState("");
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  const validSO = /^\d{3}\.\d{2}$/.test(so.trim());

  return <div className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-[var(--elo-panel)] p-6 shadow-sm lg:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-700">ELO · Planejamento/PCP</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Solicitação → Checklist → Orçamento → Revisão</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-500">Orçamento é setor interno de Planejamento/PCP. Nenhuma ação externa ocorre antes da revisão do analista.</p></div><span className="rounded-full border border-teal-200 bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-800">Setor interno: Orçamento</span></div><div className="mt-7 grid gap-2 sm:grid-cols-4">{(["solicitacao", "checklist", "orcamento", "revisao"] as const).map((item, index) => <button key={item} type="button" onClick={() => setStage(item)} className={`rounded-xl border px-3 py-3 text-left text-sm font-semibold ${stage === item ? "border-teal-600 bg-teal-700 text-white" : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"}`}><span className="mr-2 text-xs opacity-80">0{index + 1}</span>{item === "solicitacao" ? "Solicitação" : item === "checklist" ? "Checklist ELO" : item === "orcamento" ? "Orçamento" : "Revisão"}</button>)}</div></section>
    {stage === "solicitacao" && <section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Identificação da SO</h3><p className="mt-1 text-sm text-slate-500">A numeração é informada pelo analista de orçamento.</p></div><span className={validSO ? "rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700" : "rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600"}>{validSO ? "Formato válido" : "Padrão SO 000.AA"}</span></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Número da SO<input value={so} onChange={(event) => setSO(event.target.value)} placeholder="000.26" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 font-mono text-sm outline-none focus:border-teal-600" /></label><label className="text-sm font-semibold">Analista responsável<input placeholder="Nome do analista" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm outline-none focus:border-teal-600" /></label><label className="text-sm font-semibold md:col-span-2">Documento e trecho de origem<textarea placeholder="Registre a fonte que sustenta a análise. Quantidades apenas quando constarem no documento ou forem informadas pelo responsável." className="mt-2 min-h-28 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm outline-none focus:border-teal-600" /></label></div><div className="mt-5 flex justify-end"><button type="button" disabled={!validSO} onClick={() => setStage("checklist")} className="rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">Abrir Checklist ELO</button></div></section>}
    {stage === "checklist" && <section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">Checklist ELO</h3><p className="mt-1 text-sm text-slate-500">Enquadramento, padrão × excedente, riscos e regras antes do orçamento.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{Object.keys(checked).length} / {checklist.length} revisados</span></div><div className="mt-5 overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Critério</th><th className="pb-3">Situação</th><th className="pb-3">Evidência ou risco</th></tr></thead><tbody>{checklist.map((item) => <tr key={item} className="border-b border-slate-100"><td className="py-4 font-medium">{item}</td><td className="py-4"><select value={checked[item] ? "revisado" : ""} onChange={(event) => setChecked((previous) => ({ ...previous, [item]: event.target.value === "revisado" }))} className="rounded-lg border border-slate-300 bg-white px-2 py-2 text-sm"><option value="">A revisar</option><option value="revisado">Revisado</option><option value="risco">Risco a validar</option><option value="na">Não se aplica</option></select></td><td className="py-4"><input placeholder="Fonte, risco ou justificativa" className="w-full rounded-lg border border-slate-300 px-2 py-2 text-sm" /></td></tr>)}</tbody></table></div><div className="mt-5 flex flex-wrap justify-between gap-3"><button type="button" onClick={() => setStage("solicitacao")} className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold">Voltar</button><button type="button" onClick={() => setStage("orcamento")} className="rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white">Revisar e abrir orçamento</button></div></section>}
    {stage === "orcamento" && <section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><h3 className="font-semibold">Composição do orçamento</h3><p className="mt-1 text-sm text-slate-500">Modelo base, excedentes e mão de obra devem ser informados com fonte. O ELO não cria quantidade ou preço.</p><div className="mt-5 grid gap-3 md:grid-cols-3">{["Modelo base", "Excedentes", "Mão de obra"].map((item) => <div key={item} className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5"><p className="font-semibold">{item}</p><p className="mt-2 text-sm leading-5 text-slate-500">Nenhum item documentado nesta análise.</p></div>)}</div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Preencha somente quantitativos e preços que tenham origem identificada e data de cotação.</div><div className="mt-5 flex flex-wrap justify-between gap-3"><button type="button" onClick={() => setStage("checklist")} className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold">Reabrir Checklist</button><button type="button" onClick={() => setStage("revisao")} className="rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white">Conferir resultado</button></div></section>}
    {stage === "revisao" && <section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><h3 className="font-semibold">Revisão do analista</h3><p className="mt-1 text-sm leading-6 text-slate-500">Confira identidade, evidências, enquadramento, quantitativos, preços e riscos antes de qualquer ação externa.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><StateCard label="SO" /><StateCard label="Checklist" /><StateCard label="Orçamento" /></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={() => setStage("solicitacao")} className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold">Editar dados</button><button type="button" onClick={() => onMission("Revisar a análise da SO e indicar pendências de evidência antes de qualquer ação externa.")} className="rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white">Consultar ELO para revisão</button></div></section>}
  </div>;
}

function CognitiveResult({ result }: { result: CognitiveResponse }) {
  return <section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">Resultado da missão</h3><p className="mt-1 text-xs text-slate-500">request {result.request_id.slice(0, 8)} · {Math.round(result.confidence * 100)}% de confiança</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{result.provenance.validation_status ?? "processada"}</span></div><div className="mt-4 space-y-3 text-sm">{Object.entries(result.response).map(([key, value]) => <div key={key}><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{key}</p><p className="mt-1 whitespace-pre-wrap leading-6">{typeof value === "string" ? value : JSON.stringify(value, null, 2)}</p></div>)}</div></section>;
}

export function EloDashboard({ onSignOut, accessToken }: Props) {
  const [areaId, setAreaId] = useState<AreaId>("pcp");
  const [mission, setMission] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const [result, setResult] = useState<CognitiveResponse | null>(null);
  const [busy, setBusy] = useState(false);
  const area = useMemo(() => areas.find((item) => item.id === areaId) ?? areas[0], [areaId]);

  async function runMission(text: string) {
    const message = text.trim();
    if (!message || busy) return;
    setBusy(true); setNotice(null); setResult(null);
    try {
      const response = await fetch("/api/cognitive", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json", Authorization: `Bearer ${accessToken}` }, cache: "no-store", body: JSON.stringify({ message, tenant_id: process.env.NEXT_PUBLIC_ELO_TENANT_ID?.trim() || "multiteiner", domain: area.id, context: { area: area.label, surface: "operational-workspace", source: "elo-web" } }) });
      const payload = await response.json().catch(() => null);
      if (!response.ok) throw new Error(typeof payload?.message === "string" ? payload.message : "Não foi possível processar a missão pelo ELO Cognitivo.");
      setResult(payload as CognitiveResponse);
      setNotice("Missão processada pelo ELO Cognitivo. Execução externa permanece atrás do boundary governado.");
      setMission("");
    } catch (error) {
      setNotice(error instanceof Error ? error.message : "Não foi possível processar a missão.");
    } finally { setBusy(false); }
  }

  return <main className="min-h-screen bg-[var(--elo-bg)] text-[var(--elo-ink)]"><div className="min-h-screen lg:grid lg:grid-cols-[244px_minmax(0,1fr)]">
    <aside className="bg-[var(--elo-sidebar)] p-5 text-white lg:min-h-screen"><div className="flex items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-xl border border-white/30 font-bold text-teal-200">E</div><div><p className="text-xl font-semibold tracking-wide">ELO</p><p className="text-[10px] uppercase tracking-[.22em] text-white/50">Multiteiner</p></div></div><div className="mt-9 px-2 text-xs uppercase tracking-[.14em] text-white/45">Planejamento/PCP</div><p className="mt-2 px-2 text-xs text-white/60">Orçamento é setor interno</p><button type="button" onClick={() => setAreaId("pcp")} className={`mt-4 w-full rounded-xl px-4 py-3 text-left text-sm font-semibold ${areaId === "pcp" ? "bg-white/15 text-white" : "text-white/70 hover:bg-white/10"}`}>▧ Fluxo de solicitações</button><div className="mt-8 border-t border-white/10 pt-5"><p className="mb-2 px-2 text-xs uppercase tracking-[.14em] text-white/45">Acesso</p><p className="px-2 text-sm text-white/75">Sessão ELO autorizada</p><button type="button" onClick={onSignOut} className="mt-5 w-full rounded-xl border border-white/15 px-4 py-3 text-left text-sm font-semibold text-white/85 hover:bg-white/10">Encerrar sessão</button></div></aside>
    <section className="min-w-0"><header className="border-b border-slate-200 bg-[var(--elo-panel)] px-5 py-4 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs text-slate-500">ELO / Workspace operacional</p><h1 className="text-2xl font-semibold tracking-tight">{area.label}</h1></div><span className="rounded-full border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">Cognitivo ativo</span></div><nav className="mt-4 flex gap-2 overflow-x-auto pb-1" aria-label="Áreas do workspace">{areas.map((item) => <button key={item.id} type="button" onClick={() => { setAreaId(item.id); setNotice(null); setResult(null); }} aria-current={item.id === areaId ? "page" : undefined} className={`shrink-0 rounded-lg border px-3 py-2 text-xs font-semibold transition ${item.id === areaId ? "border-teal-700 bg-teal-700 text-white" : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"}`}><span className="mr-1.5">{item.icon}</span>{item.label}</button>)}</nav></header>
      <div className="space-y-5 p-5 lg:p-8">{notice && <div role="status" className="rounded-xl border border-slate-200 bg-[var(--elo-panel)] px-4 py-3 text-sm text-slate-700">{notice}</div>}
        {areaId === "pcp" ? <PCPWorkspace onMission={runMission} /> : <GenericArea area={area} onOpenPCP={() => setAreaId("pcp")} />}
        <section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-semibold">Missão ELO</h3><p className="mt-1 text-sm text-slate-500">Consulta ao ELO Cognitivo no contexto da área aberta.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{busy ? "Processando" : "Pronto"}</span></div><div className="mt-4 flex gap-2 rounded-xl border border-slate-200 bg-slate-50 p-2"><input value={mission} onChange={(event) => setMission(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void runMission(mission); }} placeholder={`Solicite uma análise para ${area.label.toLowerCase()}…`} disabled={busy} className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" /><button type="button" onClick={() => void runMission(mission)} disabled={busy} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Enviar</button></div></section>
        {result && <CognitiveResult result={result} />}
      </div></section></div></main>;
}
