"use client";

import { useEffect, useMemo, useState } from "react";
import { sectors, type SectorKey } from "@/lib/sectors";
import { DEFAULT_ELO_SETTINGS, loadELOSettings, persistELOSettings, type ELOSettings } from "@/lib/elo-settings";
import { EloSettingsPanel } from "@/components/elo-settings-panel";
import type { CognitiveResponse } from "@/lib/elo-cognitive";

type Props = { onSignOut?: () => void; accessToken: string };
type Workspace = { objective: string; queue: string; automations: string[]; signals: string[] };

const navItems = ["Início", "Missões", "Projetos", "Análises", "Conectores", "Governança"];
const workspaceBySector: Record<SectorKey, Workspace> = {
  planejamento: { objective: "Decidir, orçar e encaminhar demandas", queue: "Solicitações e licitações", automations: ["Triagem de solicitação", "Checklist ELO", "Pré-análise de orçamento"], signals: ["Demanda", "Complexidade", "Evidência", "Decisão"] },
  comercial: { objective: "Transformar oportunidades em decisões comerciais", queue: "Leads, propostas e riscos", automations: ["Qualificação de lead", "Rascunho de proposta", "Alerta de risco"], signals: ["Lead", "Oportunidade", "Proposta", "Conversão"] },
  financeiro: { objective: "Projetar recursos e proteger o caixa", queue: "Receitas, despesas e previsões", automations: ["Leitura de despesas", "Previsão de fluxo", "Alerta de inadimplência"], signals: ["Caixa", "Receber", "Pagar", "Risco"] },
  rh: { objective: "Apoiar pessoas e decisões organizacionais", queue: "Pessoas e desenvolvimento", automations: ["Triagem de vaga", "Análise de clima", "Plano de desenvolvimento"], signals: ["Pessoas", "Vagas", "Clima", "Desenvolvimento"] },
  operacoes: { objective: "Orquestrar processos e remover gargalos", queue: "Processos e incidentes", automations: ["Abertura de processo", "Detecção de gargalo", "Acompanhamento de fornecedor"], signals: ["Processo", "SLA", "Incidente", "Fornecedor"] },
  pcp: { objective: "Conectar capacidade, materiais e produção", queue: "Ordens, estoque e capacidade", automations: ["Programação de produção", "Análise de estoque", "Detecção de gargalo"], signals: ["Ordem", "Capacidade", "Material", "Gargalo"] },
  ti: { objective: "Manter sistemas seguros e disponíveis", queue: "Sistemas, chamados e riscos", automations: ["Triagem de chamado", "Análise de vulnerabilidade", "Relatório operacional"], signals: ["Sistema", "Chamado", "Disponibilidade", "Segurança"] },
};
const actionHelp: Record<SectorKey, string[]> = {
  planejamento: ["Nova solicitação", "Analisar orçamento", "Consultar ELO", "Abrir relatório"], comercial: ["Qualificar lead", "Gerar proposta", "Analisar conversão", "Identificar risco"], financeiro: ["Gerar relatório", "Analisar despesas", "Prever fluxo", "Ver inadimplência"], rh: ["Abrir vaga", "Analisar clima", "Plano de desenvolvimento", "Relatório de desempenho"], operacoes: ["Iniciar processo", "Verificar gargalos", "Gerar relatório", "Acompanhar fornecedor"], pcp: ["Programar produção", "Ver Gantt", "Analisar estoque", "Detectar gargalo"], ti: ["Abrir chamado", "Ver status", "Analisar vulnerabilidades", "Gerar relatório"],
};
const descriptions: Record<SectorKey, string> = {
  planejamento: "Entrada de demandas, análise, orçamento e encaminhamento governado.", comercial: "Oportunidades, propostas e riscos comerciais.", financeiro: "Leitura financeira e apoio a decisões de recursos.", rh: "Pessoas, desenvolvimento e indicadores organizacionais.", operacoes: "Coordenação operacional, incidentes e desempenho.", pcp: "Capacidade, programação, materiais e gargalos de produção.", ti: "Sistemas, suporte, disponibilidade e segurança.",
};

function CognitiveResult({ result }: { result: CognitiveResponse }) {
  return (
    <section className="grid gap-4 xl:grid-cols-[1.5fr_0.8fr]">
      <article className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">Resultado da missão</h3><p className="mt-1 text-xs text-slate-400">request {result.request_id.slice(0, 8)} · {Math.round(result.confidence * 100)}% confiança</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{result.provenance.validation_status ?? "processada"}</span></div><div className="mt-5 space-y-3 text-sm leading-6">{Object.entries(result.response).map(([key, value]) => <div key={key}><div className="text-xs font-medium uppercase tracking-wide text-slate-400">{key}</div><div className="mt-1 whitespace-pre-wrap">{typeof value === "string" ? value : JSON.stringify(value, null, 2)}</div></div>)}</div>{result.suggestions.length > 0 && <div className="mt-5"><h4 className="text-xs font-semibold uppercase tracking-wide text-slate-400">Próximas ações</h4><div className="mt-2 flex flex-wrap gap-2">{result.suggestions.map((item) => <span key={item.action_id} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-medium text-slate-700">{item.label}{item.requires_approval ? " · aprovação" : ""}</span>)}</div></div>}</article>
      <article className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><h3 className="font-semibold">Proveniência e controle</h3><div className="mt-4 space-y-3 text-sm"><div><span className="text-slate-400">Policy</span><div>{result.provenance.policy_decision ?? "não informado"}</div></div><div><span className="text-slate-400">Agentes</span><div>{result.agents_used.map((agent) => agent.agent_id).join(", ") || "nenhum informado"}</div></div><div><span className="text-slate-400">Evidências</span><div>{result.provenance.evidence_refs.length}</div></div><div><span className="text-slate-400">Processamento</span><div>{Math.round(result.processing_time_ms)} ms</div></div></div></article>
    </section>
  );
}

export function EloDashboard({ onSignOut, accessToken }: Props) {
  const [sectorKey, setSectorKey] = useState<SectorKey>("planejamento");
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [settings, setSettings] = useState<ELOSettings>(DEFAULT_ELO_SETTINGS);
  const [activeNav, setActiveNav] = useState("Início");
  const [mission, setMission] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const [result, setResult] = useState<CognitiveResponse | null>(null);
  const [busy, setBusy] = useState(false);
  const sector = useMemo(() => sectors.find((item) => item.key === sectorKey) ?? sectors[0], [sectorKey]);
  const workspace = workspaceBySector[sectorKey];
  const actions = actionHelp[sectorKey];

  useEffect(() => { setSettings(loadELOSettings()); }, []);
  useEffect(() => { document.documentElement.dataset.theme = settings.theme; document.documentElement.style.colorScheme = settings.theme; }, [settings.theme]);
  function handleSettingsChange(next: ELOSettings) { setSettings(next); persistELOSettings(next); }
  function playFeedbackTone() { if (!settings.soundEnabled || typeof window === "undefined") return; try { const AudioContextClass = window.AudioContext ?? (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) return; const context = new AudioContextClass(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = 660; gain.gain.value = 0.025; oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.06); void context.close(); } catch { /* optional feedback */ } }

  async function runMission(requestText: string) {
    const request = requestText.trim(); if (!request || busy) return;
    setBusy(true); setNotice(null); setResult(null);
    try {
      const response = await fetch("/api/cognitive", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json", Authorization: `Bearer ${accessToken}` }, cache: "no-store", body: JSON.stringify({ message: request, tenant_id: process.env.NEXT_PUBLIC_ELO_TENANT_ID?.trim() || "multiteiner", principal_id: undefined, domain: sector.key, context: { sector: sector.label, surface: activeNav, workspace: workspace.objective, source: "elo-web" } }) });
      const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(typeof payload?.message === "string" ? payload.message : "Não foi possível processar a missão pelo ELO Cognitivo.");
      setResult(payload as CognitiveResponse); setNotice("Missão processada pelo ELO Cognitivo. A execução externa permanece atrás do boundary governado."); setMission(""); playFeedbackTone();
    } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível processar a missão."); } finally { setBusy(false); }
  }

  return (
    <main className="min-h-screen bg-[var(--elo-bg)] text-[var(--elo-ink)]"><div className="flex min-h-screen flex-col lg:flex-row">
      <aside className="w-full border-b border-white/10 bg-[var(--elo-sidebar)] p-4 text-white lg:min-h-screen lg:w-72 lg:border-b-0 lg:border-r"><div className="mb-8 flex items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-full border border-white/40 text-lg font-semibold">E</div><div><div className="text-xl font-semibold tracking-wide">ELO</div><div className="text-[10px] uppercase tracking-[0.24em] text-white/50">Inteligência corporativa</div></div></div><nav aria-label="Navegação principal" className="space-y-1">{navItems.map((item) => <button key={item} type="button" onClick={() => setActiveNav(item)} className={`w-full rounded-xl px-4 py-3 text-left text-sm transition ${activeNav === item ? "bg-white/10 font-medium text-white" : "text-white/70 hover:bg-white/10 hover:text-white"}`}>{item === "Início" ? "⌂" : "•"} {item}</button>)}</nav><div className="mt-8 border-t border-white/10 pt-5"><div className="mb-2 px-2 text-xs font-medium uppercase tracking-wider text-white/40">Setores</div><div className="space-y-2">{sectors.map((item) => <button key={item.key} type="button" onClick={() => { setSectorKey(item.key); setActiveNav("Início"); setNotice(null); setResult(null); }} aria-current={sectorKey === item.key ? "page" : undefined} className={`w-full rounded-xl border px-3 py-2.5 text-left text-sm transition ${sectorKey === item.key ? "border-white/20 bg-white/15 text-white" : "border-white/5 bg-white/5 text-white/65 hover:bg-white/10 hover:text-white"}`}>{item.label}</button>)}</div></div><button type="button" onClick={() => setSettingsOpen(true)} className="mt-5 flex w-full items-center justify-between rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/80 hover:bg-white/10"><span>⚙ Configurações</span><span className="text-xs text-white/40">Canais</span></button></aside>
      <section className="flex min-w-0 flex-1 flex-col"><header className="flex items-center justify-between gap-4 border-b border-slate-200 bg-[var(--elo-panel)]/90 px-5 py-4 backdrop-blur lg:px-8"><div><div className="text-xs text-slate-400">ELO / {activeNav}</div><h1 className="text-2xl font-semibold tracking-tight">{sector.label}</h1></div><div className="flex items-center gap-2"><span className="hidden rounded-full border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-500 md:inline-flex">Cognitivo ativo</span><button type="button" onClick={() => setSettingsOpen(true)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600" aria-label="Configurações">⚙</button><button type="button" onClick={onSignOut} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Sair</button><div className="hidden text-sm text-slate-500 sm:block">Bruno</div><div className="grid size-9 place-items-center rounded-full bg-slate-200 text-sm font-semibold text-slate-700">B</div></div></header>
        <div className="flex-1 space-y-6 p-5 lg:p-8">{notice && <div className="rounded-xl border border-slate-200 bg-[var(--elo-panel)] px-4 py-3 text-sm text-slate-600" role="status">{notice}</div>}
          <section className="rounded-3xl border border-slate-200 bg-[var(--elo-panel)] p-6 shadow-sm lg:p-7"><div className="flex flex-col justify-between gap-6 xl:flex-row xl:items-end"><div className="max-w-3xl"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em]" style={{ color: sector.accent }}>ELO · {sector.label}</p><h2 className="text-3xl font-semibold tracking-tight lg:text-4xl">{workspace.objective}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{descriptions[sectorKey]}</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm"><div className="text-xs uppercase tracking-wide text-slate-400">Orquestração</div><div className="mt-2 font-semibold">Intenção → Cognitivo → Simbionte → Hermes</div><div className="mt-1 text-xs text-slate-500">Evidência → Resultado → Aprendizado → Evolution Gate</div></div></div><div className="mt-7 grid gap-3 md:grid-cols-4">{workspace.signals.map((signal, index) => <div key={signal} className="relative rounded-2xl border border-slate-200 p-4"><div className="text-xs text-slate-400">{String(index + 1).padStart(2, "0")}</div><div className="mt-2 font-semibold">{signal}</div>{index < workspace.signals.length - 1 && <span className="absolute -right-2 top-1/2 hidden text-slate-300 md:block">→</span>}</div>)}</div></section>
          <div className="grid gap-4 xl:grid-cols-[1.35fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Missão ELO</h3><p className="mt-1 text-xs text-slate-400">O setor define o contexto; o Cognitivo decide o fluxo governado.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{busy ? "Processando" : "Pronto"}</span></div><div className="mt-4 flex gap-2 rounded-xl border border-slate-200 bg-slate-50 p-2"><input id="mission" value={mission} onChange={(event) => setMission(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void runMission(mission); }} placeholder={`Solicite algo para ${sector.label.toLowerCase()}…`} disabled={busy} className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none"/><button type="button" onClick={() => void runMission(mission)} disabled={busy} className="rounded-lg px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" style={{ backgroundColor: sector.accent }}>Enviar</button></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500"><div className="rounded-lg bg-slate-50 p-3">Boundary server-side</div><div className="rounded-lg bg-slate-50 p-3">Hermes não é autoridade</div></div></section><section className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><h3 className="font-semibold">Automações do setor</h3><p className="mt-1 text-xs text-slate-400">Superfícies preparadas para missões governadas e execução autorizada.</p><div className="mt-4 space-y-2">{workspace.automations.map((automation) => <button key={automation} type="button" disabled={busy} onClick={() => void runMission(automation)} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-3 py-3 text-left text-sm hover:bg-slate-50 disabled:opacity-60"><span>{automation}</span><span className="text-slate-300">→</span></button>)}</div></section></div>
          {result && <CognitiveResult result={result} />}
          <section aria-label="Indicadores principais" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{sector.metrics.map((metric) => <article key={metric.label} className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><p className="text-xs font-medium text-slate-500">{metric.label}</p><div className="mt-2 flex items-end justify-between gap-2"><strong className="text-2xl tracking-tight">{metric.value}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{metric.source === "cognitive" ? "Cognitivo" : "Sem dado"}</span></div></article>)}</section>
          <section className="grid gap-4 xl:grid-cols-[1.25fr_1fr]"><article className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Painel de orquestração</h3><p className="mt-1 text-xs text-slate-400">Visão do ciclo sem fabricar dados ainda não devolvidos pelo Cognitivo.</p></div><span className="rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-500">{workspace.queue}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 p-4"><div className="text-xs text-slate-400">Entrada</div><div className="mt-2 font-semibold">Intenção do setor</div></div><div className="rounded-xl border border-slate-200 p-4"><div className="text-xs text-slate-400">Decisão</div><div className="mt-2 font-semibold">Cognitivo + política</div></div><div className="rounded-xl border border-slate-200 p-4"><div className="text-xs text-slate-400">Execução</div><div className="mt-2 font-semibold">Symbiont / Hermes</div></div></div><div className="mt-3 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">A execução externa somente ocorre quando autorizada pelo boundary. Evidência e resultado retornam para o fluxo governado; promoção para conhecimento canônico continua sujeita ao Evolution Gate.</div></article><article className="rounded-2xl border border-slate-200 bg-[var(--elo-panel)] p-5 shadow-sm"><h3 className="font-semibold">Ações rápidas</h3><p className="mt-1 text-xs text-slate-400">Atalhos específicos do espaço {sector.label}.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-1">{actions.map((action) => <button key={action} type="button" disabled={busy} onClick={() => void runMission(action)} className="flex items-center justify-between rounded-xl border border-slate-200 px-3 py-3 text-left text-sm hover:bg-slate-50 disabled:opacity-60"><span>{action}</span><span className="text-slate-300">→</span></button>)}</div></article></section>
        </div>
      </section>
    </div><EloSettingsPanel open={settingsOpen} onClose={() => setSettingsOpen(false)} onChange={handleSettingsChange} /></main>
  );
}
