create or replace view public.v_elo_pcp_decisao_externa_resumo
with (security_invoker = true)
as
with d as (select * from public.v_elo_pcp_decisao_externa_detalhe),
comercial as (select count(distinct pedido_venda_id) as pedidos_comerciais,coalesce(sum(quantidade),0) as unidades_comerciais from public.v_elo_pcp_demanda_comercial),
operacao as (select count(*) filter(where coalesce(status,'PLANEJADO') not in ('CANCELADO','CANCELADA')) as ordens_externas,coalesce(sum(horas_planejadas) filter(where coalesce(status,'PLANEJADO') not in ('CANCELADO','CANCELADA')),0) as horas_planejadas_externas from public.mt_ordens_montagem_externa),
fatores as (select count(*) filter(where estado_fator='FATOR_CALCULADO') as fatores_calculados,count(*) filter(where estado_fator='FATOR_CALCULADO' and variacao_percentual>0) as fatores_crescimento,count(*) filter(where estado_fator='FATOR_CALCULADO' and variacao_percentual<0) as fatores_reducao,count(*) filter(where estado_comparabilidade='COMPARAVEL_POTENCIAL') as comparaveis_potenciais from d),
gaps as (select count(*) filter(where gaps_composicao>0) as linhas_com_gap_composicao,count(*) filter(where proxima_informacao_decisoria <> 'VALIDAR_IMPACTO_PROJETADO_COM_OPERACAO_E_RH') as linhas_com_informacao_pendente from d),
fonte_demanda as (select count(*) as historico_registros,coalesce(sum(quantidade_historica),0) as historico_unidades,coalesce(sum(quantidade_prevista),0) as previsao_unidades from (select distinct tenant_id,modelo_id,natureza_demanda,chave_comparabilidade,quantidade_historica,quantidade_prevista from public.v_elo_pcp_referencia_demanda_comparavel) x),
cobertura as (select count(*) as modelos_com_previsao,coalesce(sum(demanda_prevista),0) as demanda_prevista_modelos,coalesce(sum(estoque_disponivel),0) as estoque_disponivel_modelos,coalesce(sum(unidades_em_reparo_recuperaveis),0) as reparos_recuperaveis_modelos,coalesce(sum(producao_programada),0) as producao_programada_modelos,coalesce(sum(necessidade_adicional_fabricacao),0) as necessidade_adicional_fabricacao_modelos,count(*) filter(where estado_cobertura='DEFICIT_FABRICACAO') as modelos_com_deficit_fabricacao,count(*) filter(where estado_cobertura like 'GAP_REPARO_%') as modelos_com_gap_reparo,coalesce(sum(reparos_sem_unidade),0) as reparos_sem_unidade,coalesce(sum(reparos_sem_data_conclusao),0) as reparos_sem_data_conclusao from public.v_elo_pcp_cobertura_demanda_externa)
select now() as atualizado_em,
case when fd.historico_registros=0 then 'AGUARDANDO_HISTORICO' when fd.previsao_unidades=0 then 'AGUARDANDO_PREVISAO' when ft.fatores_calculados=0 then 'AGUARDANDO_VALIDACAO_DE_COMPARABILIDADE' when gg.linhas_com_gap_composicao>0 then 'AGUARDANDO_COMPOSICAO_OPERACIONAL' else 'ANALISE_DISPONIVEL_PARA_VALIDACAO' end as estado_decisao,
c.pedidos_comerciais,c.unidades_comerciais,fd.historico_registros,fd.historico_unidades,fd.previsao_unidades,ft.comparaveis_potenciais,ft.fatores_calculados,ft.fatores_crescimento,ft.fatores_reducao,o.ordens_externas,o.horas_planejadas_externas,
coalesce((select sum(x.demanda_humana_historica_media_dia) from d x where x.demanda_humana_historica_media_dia is not null),0) as demanda_humana_historica_media_total_dia,
coalesce((select sum(x.demanda_humana_projetada_media_dia) from d x where x.demanda_humana_projetada_media_dia is not null),0) as demanda_humana_projetada_media_total_dia,
gg.linhas_com_gap_composicao,gg.linhas_com_informacao_pendente,
jsonb_build_object('impactos_a_observar',jsonb_build_array('volume_comercial','variacao_da_demanda_comparavel','cobertura_por_estoque','cobertura_por_reparo','producao_ja_programada','necessidade_adicional_de_fabricacao','horas_planejadas_de_operacao_externa','demanda_humana_historica_por_funcao','demanda_humana_projetada_por_funcao','gaps_de_composicao'),'informacoes_que_aumentam_precisao',jsonb_build_array('chave_de_comparabilidade_validada','previsao_por_modelo_e_natureza','historico_real_por_modelo_e_natureza','estoque_de_unidades_modulares_com_status','ordens_de_reparo_com_unidade_e_data_de_conclusao','ordens_de_producao_com_saldo_planejado','ordens_externas_com_inicio_fim_e_horas_planejadas','composicao_funcional_validada','historico_humano_por_funcao','confiabilidade_da_previsao','origem_comercial_rastreavel'),'regra','Nao transformar crescimento de demanda em crescimento de fabricacao ou quadro de RH antes de verificar cobertura por estoque, reparo e producao programada e validar a operacao.') as guia_decisao,
cv.modelos_com_previsao,cv.demanda_prevista_modelos,cv.estoque_disponivel_modelos,cv.reparos_recuperaveis_modelos,cv.producao_programada_modelos,cv.necessidade_adicional_fabricacao_modelos,cv.modelos_com_deficit_fabricacao,cv.modelos_com_gap_reparo,cv.reparos_sem_unidade,cv.reparos_sem_data_conclusao,
case when cv.modelos_com_gap_reparo>0 then 'GAP_REPARO' when cv.modelos_com_deficit_fabricacao>0 then 'DEFICIT_FABRICACAO' when cv.modelos_com_previsao>0 then 'COBERTURA_SUFICIENTE' else 'SEM_PREVISAO' end as estado_cobertura_global
from comercial c cross join operacao o cross join fatores ft cross join gaps gg cross join fonte_demanda fd cross join cobertura cv;