-- Canonical ELO authorization schema baseline.
-- Identity, authorization-session, role, capability, scope and audit primitives.
create extension if not exists pgcrypto;
create table if not exists public.elo_identity_registry (identity_id uuid primary key default gen_random_uuid(), auth_user_id uuid unique references auth.users(id) on delete set null, provider text not null, provider_subject text not null, display_name text, enterprise_context jsonb not null default '{}'::jsonb, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (provider, provider_subject));
create table if not exists public.elo_identity_sessions (session_id uuid primary key default gen_random_uuid(), identity_id uuid not null references public.elo_identity_registry(identity_id) on delete cascade, issued_at timestamptz not null default now(), expires_at timestamptz not null, revoked_at timestamptz, last_seen_at timestamptz not null default now(), constraint elo_identity_sessions_valid_window check (expires_at > issued_at), constraint elo_identity_sessions_revoked_after_issue check (revoked_at is null or revoked_at >= issued_at));
create table if not exists public.elo_roles (role_id uuid primary key default gen_random_uuid(), code text not null unique, active boolean not null default true, description text, created_at timestamptz not null default now());
create table if not exists public.elo_capabilities (capability_id uuid primary key default gen_random_uuid(), code text not null unique, active boolean not null default true, description text, created_at timestamptz not null default now());
create table if not exists public.elo_identity_roles (identity_id uuid not null references public.elo_identity_registry(identity_id) on delete cascade, role_id uuid not null references public.elo_roles(role_id) on delete cascade, created_at timestamptz not null default now(), primary key (identity_id, role_id));
create table if not exists public.elo_role_capabilities (role_id uuid not null references public.elo_roles(role_id) on delete cascade, capability_id uuid not null references public.elo_capabilities(capability_id) on delete cascade, created_at timestamptz not null default now(), primary key (role_id, capability_id));
create table if not exists public.elo_scopes (scope_id uuid primary key default gen_random_uuid(), scope_key text not null unique, active boolean not null default true, description text, created_at timestamptz not null default now());
create table if not exists public.elo_identity_scopes (identity_id uuid not null references public.elo_identity_registry(identity_id) on delete cascade, scope_id uuid not null references public.elo_scopes(scope_id) on delete cascade, created_at timestamptz not null default now(), primary key (identity_id, scope_id));
create table if not exists public.elo_authorization_audit (audit_id uuid primary key default gen_random_uuid(), identity_id uuid references public.elo_identity_registry(identity_id) on delete set null, session_id uuid references public.elo_identity_sessions(session_id) on delete set null, action text not null, resource text, decision text not null check (decision in ('ALLOW','DENY')), reason text not null, request_id text not null, created_at timestamptz not null default now());
create table if not exists public.elo_audit_log (audit_id uuid primary key default gen_random_uuid(), actor_type text not null, actor_id uuid, operation text not null, entity_type text, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists idx_elo_identity_registry_auth_user on public.elo_identity_registry(auth_user_id);
create index if not exists idx_elo_identity_registry_provider_subject on public.elo_identity_registry(provider, provider_subject);
create index if not exists idx_elo_identity_sessions_identity on public.elo_identity_sessions(identity_id);
create index if not exists idx_elo_identity_sessions_active on public.elo_identity_sessions(identity_id, revoked_at, expires_at);
create index if not exists idx_elo_identity_roles_role on public.elo_identity_roles(role_id);
create index if not exists idx_elo_role_capabilities_capability on public.elo_role_capabilities(capability_id);
create index if not exists idx_elo_identity_scopes_scope on public.elo_identity_scopes(scope_id);
create index if not exists idx_elo_authorization_audit_identity on public.elo_authorization_audit(identity_id, created_at desc);
create index if not exists idx_elo_authorization_audit_request on public.elo_authorization_audit(request_id);
alter table public.elo_identity_registry enable row level security;
alter table public.elo_identity_sessions enable row level security;
alter table public.elo_roles enable row level security;
alter table public.elo_capabilities enable row level security;
alter table public.elo_identity_roles enable row level security;
alter table public.elo_role_capabilities enable row level security;
alter table public.elo_scopes enable row level security;
alter table public.elo_identity_scopes enable row level security;
alter table public.elo_authorization_audit enable row level security;
alter table public.elo_audit_log enable row level security;
revoke all on public.elo_identity_registry from anon, authenticated;
revoke all on public.elo_identity_sessions from anon, authenticated;
revoke all on public.elo_roles from anon, authenticated;
revoke all on public.elo_capabilities from anon, authenticated;
revoke all on public.elo_identity_roles from anon, authenticated;
revoke all on public.elo_role_capabilities from anon, authenticated;
revoke all on public.elo_scopes from anon, authenticated;
revoke all on public.elo_identity_scopes from anon, authenticated;
revoke all on public.elo_authorization_audit from anon, authenticated;
revoke all on public.elo_audit_log from anon, authenticated;
insert into public.elo_roles (code, description) values ('ELO_OPERATOR', 'Operador ELO com capacidade de consulta'), ('CANONICAL_ADMIN', 'Autoridade administrativa canônica do ELO') on conflict (code) do nothing;
insert into public.elo_capabilities (code, description) values ('READ', 'Consulta e leitura autorizada'), ('ADMIN', 'Operações administrativas canônicas'), ('CANONICAL_WRITE', 'Escrita na camada canônica'), ('APPROVE', 'Aprovação de mudanças protegidas') on conflict (code) do nothing;
insert into public.elo_role_capabilities (role_id, capability_id) select r.role_id, c.capability_id from public.elo_roles r cross join public.elo_capabilities c where r.code = 'ELO_OPERATOR' and c.code = 'READ' on conflict do nothing;
insert into public.elo_role_capabilities (role_id, capability_id) select r.role_id, c.capability_id from public.elo_roles r cross join public.elo_capabilities c where r.code = 'CANONICAL_ADMIN' on conflict do nothing;
