begin;

create table if not exists public.elo_orcamentos (
  id bigint generated by default as identity primary key,
  orcamento_id text not null unique,
  origem_so text,
  descricao text,
  cliente text,
  data_orcamento date,
  status text,
  contexto jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fluxo_produtivo_modular (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  nome text not null,
  modelo_id uuid,
  taxonomia_id uuid,
  versao text not null default '1.0',
  descricao text,
  lead_time_dias numeric,
  capacidade_referencia numeric,
  unidade_capacidade text,
  ativo boolean not null default true,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fluxo_produtivo_modular_etapas (
  id uuid primary key default gen_random_uuid(),
  fluxo_id uuid not null references public.fluxo_produtivo_modular(id) on delete cascade,
  ordem integer not null,
  codigo_etapa text not null,
  nome text not null,
  setor text,
  processo text,
  recurso text,
  tempo_setup_min numeric,
  tempo_unitario_min numeric,
  capacidade numeric,
  unidade_capacidade text,
  dependencias jsonb not null default '[]'::jsonb,
  materiais jsonb not null default '[]'::jsonb,
  criterios_qualidade jsonb not null default '{}'::jsonb,
  status text not null default 'ATIVO',
  observacoes text,
  created_at timestamptz not null default now(),
  unique (fluxo_id, ordem),
  unique (fluxo_id, codigo_etapa)
);

create table if not exists public.compras_fornecedor (
  id uuid primary key default gen_random_uuid(),
  fornecedor_id uuid not null references public.fornecedores(id),
  numero_compra text,
  data_compra date not null,
  origem_so text,
  documento text,
  status text,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.compras_fornecedor_itens (
  id uuid primary key default gen_random_uuid(),
  compra_id uuid not null references public.compras_fornecedor(id) on delete cascade,
  lista_mae_id uuid references public.lista_mae(id),
  codigo_item text,
  descricao text not null,
  unidade text,
  quantidade numeric,
  valor_unitario numeric,
  valor_total numeric,
  data_entrega_prevista date,
  data_entrega_real date,
  observacoes text,
  created_at timestamptz not null default now()
);

alter table public.elo_orcamento_memoria
  add constraint fk_elo_orcamento_memoria_orcamento
  foreign key (orcamento_id) references public.elo_orcamentos(orcamento_id) not valid;

alter table public.elo_orcamento_calculos_aprendidos
  add constraint fk_elo_calculo_aprendido_orcamento
  foreign key (referencia_so) references public.elo_orcamentos(orcamento_id) not valid;

alter table public.elo_orcamento_calculos_aprendidos
  add constraint fk_elo_calculo_aprendido_memoria
  foreign key (memoria_id) references public.elo_orcamento_memoria(id) not valid;

alter table public.elo_orcamento_calculo_evidencias
  add constraint fk_elo_calculo_evidencia_calculo
  foreign key (calculo_id) references public.elo_orcamento_calculos_aprendidos(id) on delete cascade not valid;

create table if not exists public.elo_orcamento_calculo_similaridades (
  id bigint generated by default as identity primary key,
  calculo_id bigint not null references public.elo_orcamento_calculos_aprendidos(id) on delete cascade,
  calculo_similar_id bigint not null references public.elo_orcamento_calculos_aprendidos(id) on delete cascade,
  similaridade numeric not null check (similaridade >= 0 and similaridade <= 1),
  metodo text not null,
  hash_padroes text,
  contexto jsonb not null default '{}'::jsonb,
  status text not null default 'CANDIDATO',
  created_at timestamptz not null default now(),
  unique (calculo_id, calculo_similar_id, metodo),
  check (calculo_id <> calculo_similar_id)
);

create index if not exists idx_fluxo_produtivo_modular_modelo on public.fluxo_produtivo_modular(modelo_id);
create index if not exists idx_fluxo_produtivo_modular_taxonomia on public.fluxo_produtivo_modular(taxonomia_id);
create index if not exists idx_fluxo_etapas_fluxo_ordem on public.fluxo_produtivo_modular_etapas(fluxo_id, ordem);
create index if not exists idx_compras_fornecedor_fornecedor_data on public.compras_fornecedor(fornecedor_id, data_compra desc);
create index if not exists idx_compras_itens_lista_data on public.compras_fornecedor_itens(lista_mae_id, created_at desc);
create index if not exists idx_calculos_aprendidos_orcamento on public.elo_orcamento_calculos_aprendidos(referencia_so);
create index if not exists idx_calculos_aprendidos_memoria on public.elo_orcamento_calculos_aprendidos(memoria_id);
create index if not exists idx_calculos_aprendidos_hash on public.elo_orcamento_calculos_aprendidos(hash_calculo);
create index if not exists idx_calculo_similaridades_calculo on public.elo_orcamento_calculo_similaridades(calculo_id, similaridade desc);
create index if not exists idx_calculo_similaridades_similar on public.elo_orcamento_calculo_similaridades(calculo_similar_id, similaridade desc);

insert into public.elo_orcamentos (orcamento_id, origem_so, status)
select distinct x.orcamento_id, x.orcamento_id, 'REFERENCIA_EXISTENTE'
from (
  select orcamento_id from public.elo_orcamento_memoria where orcamento_id is not null
  union select orcamento_id from public.elo_orcamento_decisoes where orcamento_id is not null
  union select referencia_so from public.elo_orcamento_calculos_aprendidos where referencia_so is not null
  union select ultimo_orcamento_id from public.elo_orcamento_associacoes where ultimo_orcamento_id is not null
) x
where trim(x.orcamento_id) <> ''
on conflict (orcamento_id) do nothing;

commit;
